SEARCH_TEXT: '搜索'
OFFICIAL_ACCOUNTS_TEXT: '公众号'
MOMENT_DETAILED_PAGE_PRAISE_TEXT: '赞'
ENGLISH_QUOTE_NAME_TEXT: '英语短句每日分享'


OFFICIAL_ACCOUNTS_PAGE_SEARCH_BUTTON_ID: 'com.tencent.mm:id/jy'
SUBSCRIPTION_PAGE_HISTORY_TEXT: 'History'
ME_PAGE_MY_POST_TEXT: '相册'
MOMENT_PAGE_ME_TEXT: '我的相册'
ARTICLE_PAGE_AD_TEXT: '广告 '


MAIN_PAGE_WEIXIN_TEXT: '微信'
MAIN_PAGE_CONTACT_TEXT: '通讯录'
MAIN_PAGE_DISCOVER_TEXT: '发现'
MAIN_PAGE_ME_TEXT: '我'


MY_POST_PAGE_MOMENT_PIC_ID: 'com.tencent.mm:id/dep'
MY_POST_PAGE_MOMENT_ARTICLE_ID: 'com.tencent.mm:id/yk'


SEARCH_PAGE_SEARCH_TEXT_BOX_ID: 'com.tencent.mm:id/kh'
SEARCH_PAGE_SEARCH_RESULT_CLASS: 'android.widget.TextView'



ARTICLE_LIST_PAGE_SEARCH_ARTICLE_TEXT: '搜索公众号文章'
ARTICLE_LIST_PAGE_HISTORY_ARTICLE_TEXT: '历史消息'





