MAIN_PAGE_WEIXIN_TEXT: '微信'
MAIN_PAGE_CONTACT_TEXT: '通讯录'
MAIN_PAGE_DISCOVER_TEXT: '发现'
MAIN_PAGE_ME_TEXT: '我'

ME_PAGE_MY_POST_TEXT: '相册'
MOMENT_PAGE_ME_TEXT: '我'

MY_POST_PAGE_MOMENT_PIC_ID: 'visible == true AND name CONTAINS "月"'
MY_POST_PAGE_MOMENT_YESTERDAY_ID: 'name CONTAINS "昨天"'
#visible == true AND
MOMENT_DETAILED_PAGE_PRAISE_TEXT: '赞'